# Generated by Django 3.2.9 on 2021-11-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browsinghistory',
            old_name='boards',
            new_name='board',
        ),
    ]
