# Generated by Django 3.2.9 on 2021-11-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0003_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='search_user_id',
            new_name='search_user',
        ),
    ]
