# Generated by Django 3.2.8 on 2021-10-27 17:54

from django.db import migrations, models
import django.utils.timezone
import room.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=20, unique=True)),
                ('representative_person_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('work_time', models.IntegerField(null=True)),
                ('subject_to', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('layer_group_name', models.CharField(max_length=32)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to=room.models.image_directory_path)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
