# Generated by Django 3.2.8 on 2021-10-27 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default=uuid.UUID('b1da1526-2e4d-42b5-84e0-b16f1ed9b806'), max_length=32),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='representative_person_name',
            field=models.CharField(max_length=10),
        ),
    ]
