# Generated by Django 3.2.8 on 2021-10-27 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20211028_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='group_image',
            new_name='room_image',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default=uuid.UUID('351a010d-0583-41bf-bb46-fc5589fabdf2'), max_length=32),
        ),
    ]
