# Generated by Django 3.2.8 on 2021-10-28 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20211028_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default=uuid.UUID('948c2798-67d8-4b00-9899-332bfed5a437'), max_length=32),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
