# Generated by Django 3.2.8 on 2021-10-28 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0005_auto_20211028_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default=uuid.UUID('08b77b7f-c064-49f4-bf01-47cee87e960e'), max_length=32),
        ),
        migrations.CreateModel(
            name='RoomJoining',
            fields=[
                ('joininig_if', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_room_id', to='room.rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_joining',
            },
        ),
    ]
