# Generated by Django 3.2.8 on 2021-10-28 02:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20211028_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomjoining',
            old_name='joininig_if',
            new_name='joininig_id',
        ),
        migrations.RenameField(
            model_name='roomjoining',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roomjoining',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default=uuid.UUID('834359e0-dbe6-4b16-b863-f7d36da85ba7'), max_length=32),
        ),
    ]
