# Generated by Django 3.2.8 on 2021-10-28 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20211028_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default=uuid.UUID('d83a373d-75ac-4c78-9ec7-2236fb2d8045'), max_length=32),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='subject_to',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
