# Generated by Django 3.2.8 on 2021-10-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_rooms_layer_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='layer_group_name',
            field=models.CharField(default='61b245c6-bc6a-45e1-b145-dcf5b6a04cf6', max_length=36),
        ),
    ]
