# Generated by Django 3.2.8 on 2021-10-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_rooms_layer_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='layer_group_name',
        ),
    ]
