# Generated by Django 3.2.8 on 2021-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_remove_rooms_layer_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='week',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
