# Generated by Django 3.2.8 on 2021-11-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_rooms_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='week',
            new_name='week_at',
        ),
    ]
