# Generated by Django 3.2.8 on 2021-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_rename_week_rooms_week_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomjoining',
            name='spot_id',
            field=models.IntegerField(null=True),
        ),
    ]
