# Generated by Django 3.2.8 on 2021-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_roomjoining_spot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='university',
            field=models.CharField(default='宮崎大学', max_length=30),
            preserve_default=False,
        ),
    ]
