# Generated by Django 3.2.9 on 2021-11-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_roommessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommessage',
            old_name='room_id',
            new_name='room',
        ),
    ]
