# Generated by Django 3.2.10 on 2021-12-26 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_rename_room_id_roommessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomjoining',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
