# Generated by Django 3.2.10 on 2021-12-26 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_roomjoining_last_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
