# Generated by Django 3.2.10 on 2021-12-27 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_rooms_last_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_rename_notification_date_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='notification',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.rooms'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
