# Generated by Django 3.2.10 on 2021-12-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='display_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
