# Generated by Django 3.2.8 on 2021-11-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='spot_num',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='user_id',
            new_name='user',
        ),
    ]
