# Generated by Django 3.2.8 on 2021-10-24 16:14

import accounts.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.IntegerField(default=10)),
                ('university', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('laboratory', models.CharField(blank=True, max_length=10, null=True)),
                ('part_time_job', models.CharField(blank=True, max_length=8, null=True)),
                ('circle', models.CharField(blank=True, max_length=8, null=True)),
                ('hometown', models.CharField(blank=True, max_length=10, null=True)),
                ('high_school', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.CharField(blank=True, max_length=250, null=True)),
                ('sns_link_twitter', models.CharField(blank=True, max_length=254, null=True)),
                ('sns_link_instagram', models.CharField(blank=True, max_length=254, null=True)),
                ('sns_link_facebook', models.CharField(blank=True, max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
