# Generated by Django 3.2.8 on 2021-10-24 17:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_directory_path),
        ),
        migrations.AddField(
            model_name='users',
            name='user_icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_directory_path),
        ),
    ]
