# Generated by Django 3.2.8 on 2021-10-26 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211025_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('follows_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('follower_confirm', models.BooleanField(default=False)),
                ('followee_confirm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_id', to=settings.AUTH_USER_MODEL)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
            },
        ),
    ]
