# Generated by Django 3.2.8 on 2021-10-26 17:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211027_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_background_image',
            field=models.ImageField(blank=True, default='/static/image/background_image.jpg', null=True, upload_to=accounts.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_icon_image',
            field=models.ImageField(blank=True, default='/static/image/user.svg', null=True, upload_to=accounts.models.image_directory_path),
        ),
    ]
