# Generated by Django 3.2.8 on 2021-10-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211027_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='followee_id',
            new_name='followee',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
