# Generated by Django 3.2.8 on 2021-10-31 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211028_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChatLayerGroup',
            fields=[
                ('group_name', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_bloking', models.BooleanField(default=False)),
                ('inviter_bloking', models.BooleanField(default=False)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_chat_layer_group',
            },
        ),
    ]
