# Generated by Django 3.2.8 on 2021-10-31 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_personalchatlayergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchatlayergroup',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
