# Generated by Django 3.2.9 on 2021-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_personalchatlayergroup_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='division',
            field=models.CharField(max_length=12),
        ),
    ]
