# Generated by Django 3.2.10 on 2022-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pointshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
