# Generated by Django 3.2.10 on 2022-01-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pointshistory_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointshistory',
            old_name='consumed_type',
            new_name='is_consumption',
        ),
    ]
