# Generated by Django 3.2.9 on 2021-11-27 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoppoFileStructure',
            fields=[
                ('directory', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=40)),
                ('data_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upward_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoppo.stoppofilestructure')),
            ],
            options={
                'db_table': 'stoppo_file_structure',
            },
        ),
    ]
