# Generated by Django 3.2.9 on 2021-11-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppofilestructure',
            name='upward_directory',
            field=models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to='stoppo.stoppofilestructure'),
        ),
    ]
