# Generated by Django 3.2.9 on 2021-11-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0002_alter_stoppofilestructure_upward_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppofilestructure',
            name='upward_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoppo.stoppofilestructure'),
        ),
    ]
