# Generated by Django 3.2.9 on 2021-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0004_alter_stoppofilestructure_upward_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoppofilestructure',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
