# Generated by Django 3.2.9 on 2021-12-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0006_sharefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharefile',
            old_name='file_id',
            new_name='file',
        ),
    ]
