# Generated by Django 3.2.9 on 2021-12-03 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stoppo', '0009_rename_file_sharefile_shared_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('upload_file', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=30)),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upward_directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stoppo.stoppofilestructure')),
            ],
            options={
                'db_table': 'upload_file',
            },
        ),
    ]
