# Generated by Django 3.2.9 on 2021-12-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0010_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload_file',
            new_name='upload_file_id',
        ),
    ]
