# Generated by Django 3.2.9 on 2021-12-03 13:03

from django.db import migrations, models
import stoppo.models


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0011_rename_upload_file_uploadfile_upload_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(null=True, upload_to=stoppo.models.stoppo_file_path),
        ),
    ]
