# Generated by Django 3.2.9 on 2021-12-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0012_uploadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
