# Generated by Django 3.2.9 on 2021-12-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0014_auto_20211204_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharefile',
            name='extension',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
