# Generated by Django 3.2.9 on 2021-12-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoppo', '0017_auto_20211204_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='is_root',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
