# Generated by Django 3.2.9 on 2021-11-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='ground',
            new_name='ground_id',
        ),
    ]
