# Generated by Django 3.2.9 on 2021-11-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_rename_room_id_roommessage_room'),
        ('ground', '0002_rename_ground_ground_ground_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='post_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.rooms'),
        ),
    ]
