# Generated by Django 3.2.9 on 2021-11-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0003_alter_ground_post_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='ground_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
