# Generated by Django 3.2.8 on 2021-10-30 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('board_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=800, null=True)),
                ('board_attachment_image', models.ImageField(blank=True, null=True, upload_to='board_attachment_image/')),
                ('board_attachment_file', models.FileField(blank=True, null=True, upload_to='board_attachment_file/', verbose_name='添付ファイル')),
                ('tags', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bet_points', models.IntegerField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
    ]
