# Generated by Django 3.2.8 on 2021-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_boards_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='display_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
