# Generated by Django 3.2.8 on 2021-10-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boards_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='display_name',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
