# Generated by Django 3.2.8 on 2021-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_boards_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='board_attachment_file',
            new_name='attached_file',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='board_attachment_image',
            new_name='attached_image',
        ),
        migrations.AlterField(
            model_name='boards',
            name='display_name',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
