# Generated by Django 3.2.9 on 2021-11-21 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_auto_20211031_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='related_department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='comment_image/')),
                ('comment_file', models.FileField(blank=True, null=True, upload_to='comment_file/', verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_name', models.CharField(max_length=36, null=True)),
                ('comment_nickname', models.CharField(max_length=36, null=True)),
                ('comment_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boards')),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_comment',
            },
        ),
    ]
