# Generated by Django 3.2.9 on 2021-11-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20211121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='comment',
            field=models.CharField(max_length=520),
        ),
    ]
