# Generated by Django 3.2.9 on 2021-11-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_boardcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='best_board',
            field=models.BooleanField(default=False),
        ),
    ]
