# Generated by Django 3.2.9 on 2021-11-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_rename_room_id_roommessage_room'),
        ('board', '0012_auto_20211122_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='related_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.rooms'),
        ),
    ]
