# Generated by Django 3.2.9 on 2021-12-08 11:22

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_boards_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='comment_file',
            field=models.FileField(blank=True, null=True, upload_to=board.models.board_comment_file_path, verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='boardcomment',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.board_comment_file_path),
        ),
        migrations.AlterField(
            model_name='boards',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=board.models.board_file_path, verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.board_image_path),
        ),
    ]
