# Generated by Django 3.2.9 on 2021-12-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20211208_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='bet_points',
            field=models.IntegerField(null=True),
        ),
    ]
