# Generated by Django 3.2.10 on 2022-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_boards_bet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='content',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
